### ISSUE TITLE
[chore/project-setting] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by dldmsql** [everymeals/EveryMeal_Server#1]
## 작업 목록

- [x] Jacoco와 SonarlCloud 연동을 통해 CI 에서 통합 테스트와 코드 품질 검사

**Comment by Qbeom0925** [comment]
추가로 Ngrinder 부하테스트 환경설정 완료하였습니다.
![스크린샷 2023-07-09 오후 2 39 30](https://github.com/everymeals/EveryMeal_Server/assets/53048655/a664796f-20be-42a1-b407-e1c5c6d1f0d9)
