### ISSUE TITLE
[chore/java-version-11]  jdk 11 & spring boot 2.7.x 다운 그레이

### ISSUE THREAD

**Issue by Qbeom0925** [everymeals/EveryMeal_Server#12]
자바 버전을 다운그레이를 결정하였습니다.
이유는 스프링에서 자바의 공식 라이브러리에 대한 몽고디비에서 개인접근 방식을 가져가면서 스프링 충돌이 발생했습니다.

현재 두가지의 선택 사항이 있습니다.
1. JDK 17 현상 유지 : Java VMOption으로 아래의 코드를 추가해야하는 문제가 있습니다.
`--add-opens java.base/java.time=ALL-UNNAMED --add-opens java.desktop/java.awt.geom=ALL-UNNAMED --add-opens java.desktop/sun.awt.geom=ALL-UNNAMED -Duser.timezone=Asia/Seoul ` 

2. JDK 11 다운그레이

테스트 환경에서 커스텀이 문제가 발생할 것으로 예상됩니다. 아래의 링크는 spring boot mongodb 에서 올라온 이슈인데 해결이 되지 않는 이슈로 남아있어서 2번으로 선택하였습니다.

Reference.
<img width="962" alt="스크린샷 2023-08-30 오전 11 28 49" src="https://github.com/everymeals/EveryMeal_Server/assets/53048655/d360aec3-1a9c-40ce-8c94-20024a0b39c8">
https://github.com/spring-projects/spring-data-mongodb/issues/4204

**Comment by dldmsql** [comment]
[github-actions/mongo 오픈소스](https://github.com/supercharge/mongodb-github-action/blob/main/.github/workflows/test-auth.yml) 참고해서 추가하였습니다.
